import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";

import Providers from "./providers";

import "./globals.css";
export const metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  let messages;
  try {
    messages = (await import(`../../../dictionaries/${params.lang}.json`))
      .default;
  } catch (error) {
    console.log(error);
  }
  return (
    <html
      data-theme="mytheme"
      lang={params.lang}
    >
      <body>
        <NextIntlClientProvider
          locale={params.lang}
          messages={messages}
        >
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
